//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpDeskDBEntities : DbContext
    {
        public HelpDeskDBEntities()
            : base("name=HelpDeskDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Departamentos> Departamentos { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Problemas> Problemas { get; set; }
        public DbSet<RegistroSoporte> RegistroSoporte { get; set; }
        public DbSet<RegistroUsuario> RegistroUsuario { get; set; }
        public DbSet<Severidad> Severidad { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipoSolicitud> TipoSolicitud { get; set; }
        public DbSet<TipoUser> TipoUser { get; set; }
    }
}
