//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroUsuario
    {
        public int Id { get; set; }
        public Nullable<int> IdTipoUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string Contrasena { get; set; }
        public string Email { get; set; }
        public Nullable<int> DepartamentId { get; set; }
    }
}
